version: '3.8'
services:
  gophkeeper:
    image: go-yandex-gophkeeper:local
    container_name: vigorous_williamson
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on: 
     - postgresql
     - minio
    networks:
      - goph

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: miniostore 
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on: 
      - postgresql  
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - ./data_minio:/data
    networks:
      - goph  

  postgresql:
    image: postgres:15-alpine
    container_name: ps-psql
    ports:
      - "25432:5432"
    environment: 
      - POSTGRES_DB=gophkeeper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - goph    

networks:
  goph:
    driver: bridge 
